 export const series = [
    "3 séries de 12 repetições",
    "4 séries de 10 repetições",
    "3 séries de 15 repetições",
    "3 séries de 1 minuto",
    "4 séries de 12 repetições",
    "3 séries de 10 repetições",
    "3 séries de 12 repetições",
    "3 séries de 10 repetições",
    "4 séries de 15 repetições",
    "3 séries de 12 repetições",
    "3 séries de 15 repetições",
    "3 séries de 12 repetições",
    "3 séries de 10 repetições",
    "4 séries de 20 repetições",
    "3 séries de 15 repetições",
    "3 séries de 8 repetições",
    "20 minutos",
    " 3 séries de 8 repetições",
    "3 séries de 10 repetições",
    "3 séries de 15 repetições"
  ];