export let exercicios =   ["Agachamento",
    "Supino Reto",
    "Supino Inclinado",
    "Supino Declinado",
    "Leg Press",
    "Extensão de Joelhos",
    "Flexão de Joelhos",
    "Rosca Direta",
    "Rosca Alternada",
    "Rosca Concentrada",
    "Rosca Martelo",
    "Tríceps na Polia",
    "Tríceps Testa",
    "Tríceps Corda",
    "Remada Curvada",
    "Remada Unilateral",
    "Pulldown",
    "Barra Fixa",
    "Elevação Lateral",
    "Elevação Frontal",
    "Desenvolvimento com Barra",
    "Desenvolvimento com Halteres",
    "Stiff",
    "Terra",
    "Crucifixo",
    "Crucifixo Inclinado",
    "Abdominal Reto",
    "Abdominal Oblíquo",
    "Prancha Isométrica",
    "Elevação de Quadril",
    "Flexão de Braços",
    "Burpee",
    "Corrida na Esteira",
    "Bike Ergométrica",
    "Panturrilha Sentado",
    "Panturrilha em Pé",
    "Step Up",
    "Avanço (Lunge)",
    "Good Morning",
    "Pull Over",
    "Crossover na Polia",
    "Remada Baixa",
    "Remada Cavalinho",
    "Elevação de Ombros (Encolhimento)",
    "Kettlebell Swing",
    "Mountain Climber",
    "Levantamento Olímpico",
    "Ponte para Glúteos",
    "Flexão com Rotação"
];